# Explore Results from Param Exploration

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import h5py
import copy
import pandas as pd
from scipy import optimize
from matplotlib import pyplot as plt
import pickle
from itertools import cycle
import matplotlib.colors as mcolors
from photochem.utils import stars
import PICASO_Climate_grid_121625 as picaso_grid
import Photochem_grid_121625 as photochem_grid
from picaso.photochem import EquilibriumChemistry

/mnt/c/Users/lily/Documents/NASAUWPostbac/MiniNeptuneGrid26_PostBac/Installation&Setup_Instructions/picasofiles/reference
/mnt/c/Users/lily/Documents/NASAUWPostbac/MiniNeptuneGrid26_PostBac/Installation&Setup_Instructions/picasofiles/grp/redcat/trds


In [ ]:
def plot_PT_Photochem(total_flux=None, planet_metal=None, tint=None, kzz=None, phase=None, calc_PT=True, calc_PhotCh=True, calc_RSM=False):
    
    PT_list, sol_dict, soleq_dict, wno, albedo, fpfs, PT_list_Photochem = GraphsKey.find_all_plotting_values(total_flux=total_flux, planet_metal=planet_metal, tint=tint, kzz=kzz, phase=phase, calc_PT=calc_PT, calc_PhotCh=calc_PhotCh, calc_RSM=calc_RSM)
    
    # Plot the Composition from Photochem
    fig, ax1 = plt.subplots(1,1,figsize=[8,6])
    #species = ['CO2','H2O','CH4','CO','NH3','H2','HCN','H2Oaer']
    species_sol = ['CO2_sol','H2O_sol','CH4_sol','CO_sol','NH3_sol','H2_sol','HCN_sol','H2Oaer_sol']
    species_soleq = ['CO2_soleq','H2O_soleq','CH4_soleq','CO_soleq','NH3_soleq','H2_soleq','HCN_soleq','H2Oaer_soleq']
    
    #for i,sp in enumerate(species):
    #    ax1.plot(sol_dict[sp],sol_dict['pressure']/1e6,label=sp, c='C'+str(i))
    #    ax1.plot(soleq_dict[sp],soleq_dict['pressure']/1e6, ls=':', c='C'+str(i), alpha=0.4)
    
    #for i,sp in enumerate(species_soleq):
    #    ax1.plot(soleq_dict[sp],soleq_dict['pressure_soleq']/1e6, ls=':', c='C'+str(i), alpha=0.4)
    #for i,sp in enumerate(species_sol):
    #    ax1.plot(sol_dict[sp],sol_dict['pressure_sol']/1e6, c='C'+str(i), label=sp.rstrip('_sol'))
    
    ax1.set_xscale('log')
    ax1.set_yscale('log')
    ax1.set_xlim(1e-8,1)
    ax1.set_ylim(1e+3,1e-6)
    ax1.grid(alpha=0.4)
    ax1.legend(ncol=1,bbox_to_anchor=(1,1.0),loc='upper left')
    ax1.set_xlabel('Mixing Ratio', fontsize=16)
    ax1.set_ylabel('Pressure (bar)', fontsize=16)
    #ax1.set_yticks(10.0**np.arange(-6,2))
    ax1.tick_params(axis='x', labelsize=16) 
    ax1.tick_params(axis='y', labelsize=16)
    #ax1.text(0.02, 1.04, 't = '+'%.2e'%pc.wrk.tn, \
    #    size = 15,ha='left', va='bottom',transform=ax1.transAxes)
    
    ax2 = ax1.twiny()
    ax2.set_xlabel('Temperature (K)', fontsize=16)
    ax2.set_xlim(0, 2000)
    ax2.tick_params(axis='x', labelsize=16)
    #print(((PT_list_Photochem[1])/(10**6)),  PT_list_Photochem[0])
    #print(np.flip(PT_list[1]), np.flip(PT_list[0]))
    #ax2.invert_yaxis()
    ax2.plot(PT_list_Photochem[1], (PT_list_Photochem[0]/(10**6)), c='blue', ls='--',label='PT Photochem Profile')
    
    plt.title('K2-18b Around Sun (G-Star)', fontsize=20)
    
    #plt.legend()
    
    # Save the plot as a PNG image
    #plt.tight_layout()
    #plt.savefig('AllCaseMatch_EX_with_PT_Photochem.png')
    
    plt.show()
    
    # Close the plot to free up memory (important if you're generating many plots)
    # plt.close()

# Load data files

In [22]:
filename_picaso ='results/PICASO_climate_updatop_paramext_K218b.h5'

with h5py.File(filename_picaso, 'r') as f:
    picaso_data = f
    print(list(picaso_data['inputs'][0]))
    for inputs in picaso_data['inputs']:
        print(inputs)
        plot_PT_Photochem(total_flux=None, planet_metal=None, tint=None, kzz=None, phase=None, calc_PT=True, calc_PhotCh=True, calc_RSM=False)

[1.6, 0.5, 20.0, 0.3, 0.01]
[1.6e+00 5.0e-01 2.0e+01 3.0e-01 1.0e-02]
[ 1.6  0.5 20.   0.3  1. ]
[1.6e+00 5.0e-01 2.0e+01 1.0e+01 1.0e-02]
[ 1.6  0.5 20.  10.   1. ]
[1.6e+00 5.0e-01 4.0e+02 3.0e-01 1.0e-02]
[1.6e+00 5.0e-01 4.0e+02 3.0e-01 1.0e+00]
[1.6e+00 5.0e-01 4.0e+02 1.0e+01 1.0e-02]
[  1.6   0.5 400.   10.    1. ]
[1.6e+00 3.5e+00 2.0e+01 3.0e-01 1.0e-02]
[ 1.6  3.5 20.   0.3  1. ]
[1.6e+00 3.5e+00 2.0e+01 1.0e+01 1.0e-02]
[ 1.6  3.5 20.  10.   1. ]
[1.6e+00 3.5e+00 4.0e+02 3.0e-01 1.0e-02]
[1.6e+00 3.5e+00 4.0e+02 3.0e-01 1.0e+00]
[1.6e+00 3.5e+00 4.0e+02 1.0e+01 1.0e-02]
[  1.6   3.5 400.   10.    1. ]
[4.e+00 5.e-01 2.e+01 3.e-01 1.e-02]
[ 4.   0.5 20.   0.3  1. ]
[4.e+00 5.e-01 2.e+01 1.e+01 1.e-02]
[ 4.   0.5 20.  10.   1. ]
[4.e+00 5.e-01 4.e+02 3.e-01 1.e-02]
[4.e+00 5.e-01 4.e+02 3.e-01 1.e+00]
[4.e+00 5.e-01 4.e+02 1.e+01 1.e-02]
[  4.    0.5 400.   10.    1. ]
[4.0e+00 3.5e+00 2.0e+01 3.0e-01 1.0e-02]
[ 4.   3.5 20.   0.3  1. ]
[4.0e+00 3.5e+00 2.0e+01 1.0e+01 1.0e-02

In [ ]:
filename_photochem ='results/Photochem_1D_updatop_paramext_K218b.h5'

with h5py.File(filename_photochem, 'r') as f:
    photochem_data = f
    print(list(photochem_data['results']))